# Generated by Django 2.0.3 on 2018-04-01 17:15

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=100)),
                ('timezone', models.CharField(default='GMT', max_length=100)),
                ('accountstatus', models.CharField(choices=[('FREETRIAL', 'FREETRIAL'), ('PAID', 'PAID')], default='FREETRIAL', max_length=50)),
                ('signup_timestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('comment_text', models.TextField(max_length=10000)),
                ('linked_object_type', models.CharField(choices=[('VEHICLE', 'VEHICLE'), ('REMINDER', 'REMINDER'), ('ISSUE', 'ISSUE'), ('FUELENTRY', 'FUELENTRY'), ('SERVICEENTRY', 'SERVICEENTRY')], max_length=20)),
                ('linked_object_id', models.IntegerField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FleetXApp.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=30)),
                ('contacttype', models.CharField(choices=[('OWNER', 'OWNER'), ('EMPLOYEE', 'EMPLOYEE'), ('DRIVER', 'DRIVER'), ('TECHNICIAN', 'TECHNICIAN')], default='OWNER', max_length=50)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FleetXApp.Account')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=500)),
                ('file_type', models.CharField(choices=[('IMAGE', 'IMAGE'), ('DOCUMENT', 'DOCUMENT')], max_length=20)),
                ('linked_object_type', models.CharField(choices=[('VEHICLE', 'VEHICLE'), ('REMINDER', 'REMINDER'), ('ISSUE', 'ISSUE'), ('FUELENTRY', 'FUELENTRY'), ('SERVICEENTRY', 'SERVICEENTRY')], max_length=20)),
                ('linked_object_id', models.IntegerField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FleetXApp.Account')),
            ],
        ),
        migrations.CreateModel(
            name='MasterMakes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_make', models.CharField(max_length=30)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FleetXApp.Account')),
            ],
        ),
        migrations.CreateModel(
            name='MasterModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_model', models.CharField(max_length=30)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FleetXApp.Account')),
                ('vehicle_make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FleetXApp.MasterMakes')),
            ],
        ),
        migrations.CreateModel(
            name='MasterVehicleReminderTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(max_length=70)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FleetXApp.Account')),
            ],
        ),
        migrations.CreateModel(
            name='MasterVehicleStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_status', models.CharField(max_length=30)),
                ('color', models.CharField(max_length=30)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FleetXApp.Account')),
            ],
        ),
        migrations.CreateModel(
            name='MasterVehicleTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(max_length=30)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FleetXApp.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Signups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=100)),
                ('organization_name', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('registration_number', models.CharField(max_length=30)),
                ('vehicle_color', models.CharField(max_length=30)),
                ('year', models.IntegerField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FleetXApp.Account')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FleetXApp.Contact')),
                ('make', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FleetXApp.MasterMakes')),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FleetXApp.MasterModels')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FleetXApp.MasterVehicleStatus')),
                ('vehicle_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FleetXApp.MasterVehicleTypes')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleReminders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField()),
                ('days_treshold', models.IntegerField()),
                ('email_notifications', models.BooleanField()),
                ('comments', models.TextField(blank=True, max_length=10000, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FleetXApp.Account')),
                ('notify_contacts', models.ManyToManyField(blank=True, related_name='reminders', to='FleetXApp.Contact')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FleetXApp.Vehicle')),
                ('vehicle_reminder_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FleetXApp.MasterVehicleReminderTypes')),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FleetXApp.Account')),
            ],
        ),
        migrations.AddField(
            model_name='comments',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FleetXApp.Contact'),
        ),
    ]
