# Generated by Django 2.0.3 on 2018-04-09 01:19

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=100)),
                ('timezone', models.CharField(default='GMT', max_length=100)),
                ('accountstatus', models.CharField(choices=[('FREETRIAL', 'FREETRIAL'), ('PAID', 'PAID')], default='FREETRIAL', max_length=50)),
                ('signup_timestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('comment_text', models.TextField(max_length=10000)),
                ('linked_object_type', models.CharField(choices=[('Vehicle', 'Vehicle'), ('VehicleRenewalReminder', 'VehicleRenewalReminder'), ('ServiceReminders', 'ServiceReminders'), ('Issues', 'Issues'), ('FuelEntry', 'FuelEntry'), ('ServiceEntry', 'ServiceEntry'), ('Contact', 'Contact')], max_length=20)),
                ('linked_object_id', models.IntegerField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FleetXApp.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_driver', models.BooleanField(default=False)),
                ('is_owner', models.BooleanField(default=False)),
                ('is_user', models.BooleanField(default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FleetXApp.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('uuid', models.CharField(max_length=500)),
                ('url', models.CharField(max_length=500)),
                ('file_type', models.CharField(choices=[('IMAGE', 'IMAGE'), ('DOCUMENT', 'DOCUMENT')], max_length=20)),
                ('linked_object_type', models.CharField(choices=[('Vehicle', 'Vehicle'), ('VehicleRenewalReminder', 'VehicleRenewalReminder'), ('ServiceReminders', 'ServiceReminders'), ('Issues', 'Issues'), ('FuelEntry', 'FuelEntry'), ('ServiceEntry', 'ServiceEntry'), ('Contact', 'Contact')], max_length=20)),
                ('linked_object_id', models.IntegerField()),
                ('upload_timestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FleetXApp.Account')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='FleetXApp.Contact')),
            ],
        ),
        migrations.CreateModel(
            name='FuelEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('price', models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=10)),
                ('quantity', models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=10)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FleetXApp.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Issues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reported_date', models.DateField()),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, max_length=10000, null=True)),
                ('current_status', models.CharField(choices=[('OPEN', 'OPEN'), ('WORKING', 'WORKING'), ('CLOSED', 'CLOSED')], max_length=200)),
                ('due_date', models.DateField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FleetXApp.Account')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FleetXApp.Contact')),
            ],
        ),
        migrations.CreateModel(
            name='MasterMakes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_make', models.CharField(max_length=30)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FleetXApp.Account')),
            ],
        ),
        migrations.CreateModel(
            name='MasterModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_model', models.CharField(max_length=30)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FleetXApp.Account')),
                ('vehicle_make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FleetXApp.MasterMakes')),
            ],
        ),
        migrations.CreateModel(
            name='MasterServiceReminderTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(max_length=70)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FleetXApp.Account')),
            ],
        ),
        migrations.CreateModel(
            name='MasterVehicleRenewalReminderType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(max_length=70)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FleetXApp.Account')),
            ],
        ),
        migrations.CreateModel(
            name='MasterVehicleStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_status', models.CharField(max_length=30)),
                ('color', models.CharField(max_length=30)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FleetXApp.Account')),
            ],
        ),
        migrations.CreateModel(
            name='MasterVehicleTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(max_length=30)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FleetXApp.Account')),
            ],
        ),
        migrations.CreateModel(
            name='MasterVendorTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_type', models.CharField(max_length=100)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FleetXApp.Account')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_amount', models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=10)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FleetXApp.Account')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceReminders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('odometer_reading', models.IntegerField()),
                ('odometer_treshold', models.IntegerField()),
                ('email_notifications', models.BooleanField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FleetXApp.Account')),
                ('notify_contacts', models.ManyToManyField(blank=True, related_name='servicereminders', to='FleetXApp.Contact')),
                ('service_reminder_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FleetXApp.MasterServiceReminderTypes')),
            ],
        ),
        migrations.CreateModel(
            name='Signups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=100)),
                ('organization_name', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('registration_number', models.CharField(max_length=30)),
                ('year', models.IntegerField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FleetXApp.Account')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FleetXApp.Contact')),
                ('make', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FleetXApp.MasterMakes')),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FleetXApp.MasterModels')),
                ('profilepicture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='FleetXApp.Files')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FleetXApp.MasterVehicleStatus')),
                ('vehicle_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FleetXApp.MasterVehicleTypes')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleRenewalReminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField()),
                ('days_treshold', models.IntegerField()),
                ('email_notifications', models.BooleanField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FleetXApp.Account')),
                ('notify_contacts', models.ManyToManyField(blank=True, related_name='reminders', to='FleetXApp.Contact')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FleetXApp.Vehicle')),
                ('vehicle_reminder_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FleetXApp.MasterVehicleRenewalReminderType')),
            ],
        ),
        migrations.CreateModel(
            name='Vendors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FleetXApp.Account')),
                ('vendor_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='FleetXApp.MasterVendorTypes')),
            ],
        ),
        migrations.AddField(
            model_name='servicereminders',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FleetXApp.Vehicle'),
        ),
        migrations.AddField(
            model_name='serviceentry',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FleetXApp.Vehicle'),
        ),
        migrations.AddField(
            model_name='serviceentry',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='FleetXApp.Vendors'),
        ),
        migrations.AddField(
            model_name='issues',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FleetXApp.Vehicle'),
        ),
        migrations.AddField(
            model_name='fuelentry',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FleetXApp.Vehicle'),
        ),
        migrations.AddField(
            model_name='fuelentry',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='FleetXApp.Vendors'),
        ),
        migrations.AddField(
            model_name='contact',
            name='profilepicture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='FleetXApp.Files'),
        ),
        migrations.AddField(
            model_name='contact',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comments',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FleetXApp.Contact'),
        ),
    ]
