# Generated by Django 2.0.3 on 2018-04-01 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FleetXApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterServiceReminderTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(max_length=70)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FleetXApp.Account')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceReminders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('odometer_reading', models.IntegerField()),
                ('odometer_treshold', models.IntegerField()),
                ('email_notifications', models.BooleanField()),
                ('comments', models.TextField(blank=True, max_length=10000, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FleetXApp.Account')),
                ('notify_contacts', models.ManyToManyField(blank=True, related_name='servicereminders', to='FleetXApp.Contact')),
                ('service_reminder_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FleetXApp.MasterServiceReminderTypes')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FleetXApp.Vehicle')),
            ],
        ),
    ]
