# Generated by Django 2.0.3 on 2018-04-09 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FleetXApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='email',
        ),
    ]
