# Generated by Django 2.0.3 on 2018-04-01 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FleetXApp', '0002_masterserviceremindertypes_servicereminders'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reported_date', models.DateField()),
                ('odometer_reading', models.IntegerField()),
                ('summary', models.TextField(blank=True, max_length=10000, null=True)),
                ('description', models.TextField(blank=True, max_length=10000, null=True)),
                ('current_status', models.CharField(choices=[('OPEN', 'OPEN'), ('WORKING', 'WORKING'), ('CLOSED', 'CLOSED')], max_length=200)),
                ('due_date', models.DateField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FleetXApp.Account')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FleetXApp.Contact')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FleetXApp.Vehicle')),
            ],
        ),
    ]
