# Generated by Django 2.0.3 on 2018-04-01 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FleetXApp', '0003_issues'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issues',
            name='summary',
        ),
        migrations.AddField(
            model_name='issues',
            name='title',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
