# Generated by Django 2.0.3 on 2018-04-01 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FleetXApp', '0004_auto_20180401_1852'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterVendorTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_type', models.CharField(max_length=100)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FleetXApp.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Vendors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FleetXApp.Account')),
                ('vendor_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='FleetXApp.MasterVendorTypes')),
            ],
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='account',
        ),
        migrations.AlterField(
            model_name='comments',
            name='linked_object_type',
            field=models.CharField(choices=[('Issues', 'Issues'), ('ServiceReminders', 'ServiceReminders'), ('VehicleReminders', 'VehicleReminders'), ('Vehicle', 'Vehicle')], max_length=20),
        ),
        migrations.AlterField(
            model_name='issues',
            name='odometer_reading',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Vendor',
        ),
    ]
