# Generated by Django 2.0.3 on 2018-04-01 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FleetXApp', '0005_auto_20180401_2101'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('price', models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=10)),
                ('quantity', models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=10)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FleetXApp.Account')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FleetXApp.Vehicle')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='FleetXApp.Vendors')),
            ],
        ),
    ]
