# Generated by Django 2.0.3 on 2018-04-01 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FleetXApp', '0006_fuelentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issues',
            name='odometer_reading',
        ),
    ]
