# Generated by Django 2.0.3 on 2018-04-10 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FleetXApp', '0007_odometerhistory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OdometerHistory',
            new_name='OdometerEntry',
        ),
    ]
