# Generated by Django 2.0.3 on 2018-04-07 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FleetXApp', '0008_serviceentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterContactTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_type', models.CharField(max_length=30)),
                ('color', models.CharField(max_length=30)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FleetXApp.Account')),
            ],
        ),
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='contact',
            name='is_driver',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contact',
            name='is_owner',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contacttype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='FleetXApp.MasterContactTypes'),
        ),
    ]
