# Generated by Django 2.0.3 on 2018-04-07 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FleetXApp', '0009_auto_20180407_0032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='contacttype',
            new_name='contact_type',
        ),
        migrations.AddField(
            model_name='contact',
            name='is_user',
            field=models.BooleanField(default=False),
        ),
    ]
