# Generated by Django 2.0.3 on 2018-04-07 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FleetXApp', '0010_auto_20180407_0042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mastercontacttypes',
            name='account',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='contact_type',
        ),
        migrations.DeleteModel(
            name='MasterContactTypes',
        ),
    ]
