# Generated by Django 2.0.3 on 2018-04-07 20:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FleetXApp', '0013_auto_20180407_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='upload_timestamp',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='files',
            name='uploaded_by',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='FleetXApp.Contact'),
            preserve_default=False,
        ),
    ]
