# Generated by Django 2.0.3 on 2018-04-07 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FleetXApp', '0014_auto_20180407_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='linked_object_type',
            field=models.CharField(choices=[('Vehicle', 'Vehicle'), ('VehicleReminders', 'VehicleReminders'), ('ServiceReminders', 'ServiceReminders'), ('Issues', 'Issues'), ('FuelEntry', 'FuelEntry'), ('ServiceEntry', 'ServiceEntry'), ('Contact', 'Contact')], max_length=20),
        ),
        migrations.AlterField(
            model_name='files',
            name='linked_object_type',
            field=models.CharField(choices=[('Vehicle', 'Vehicle'), ('VehicleReminders', 'VehicleReminders'), ('ServiceReminders', 'ServiceReminders'), ('Issues', 'Issues'), ('FuelEntry', 'FuelEntry'), ('ServiceEntry', 'ServiceEntry'), ('Contact', 'Contact')], max_length=20),
        ),
    ]
