# Generated by Django 2.0.3 on 2018-04-07 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FleetXApp', '0015_auto_20180407_2024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicereminders',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='vehiclereminders',
            name='comments',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='profilepicture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='FleetXApp.Files'),
        ),
    ]
