# Generated by Django 2.0.3 on 2018-04-07 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FleetXApp', '0016_auto_20180407_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='profilepicture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='FleetXApp.Files'),
        ),
    ]
